---
micronaut:
  server:
    port: 8080
    cors:
      enabled: true
---
datasources:
  ${serviceName}:
    url: jdbc:mariadb://cheatsheet_db:3306/${serviceName}
    username: ${dbUser}
    password: ${dbPassword}
    driverClassName: org.mariadb.jdbc.Driver
---
liquibase:
  datasources:
    ${serviceName}:
      change-log: classpath:changelog.yml
